# Generated by Django 4.0.6 on 2022-07-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoriaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductosCategorias', to='products.categorias'),
            preserve_default=False,
        ),
    ]
